Controllers/BsWebApiConfigurationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Nop.Core;
using Nop.Core.Plugins;
using Nop.Plugin.Misc.BsWebApi.Domain;
using Nop.Plugin.Misc.BsWebApi.Services;
using Nop.Services.Catalog;
using Nop.Services.Configuration;
using Nop.Services.Localization;
using Nop.Services.Security;
using Nop.Services.Stores;
using Nop.Services.Logging;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Kendoui;
using Nop.Web.Framework.Mvc;
using Nop.Plugin.Misc.BsWebApi.Models.DashboardModel;
using Nop.Services.Media;
using Nop.Services.Vendors;
using Nop.Core.Domain.Catalog;
using Nop.Web.Framework;
using Nop.Services.Seo;
using Nop.Plugin.Misc.BsWebApi.Models.Catalog;
using Nop.Plugin.Misc.BsWebApi.Extensions;
using Nop.Plugin.Misc.BsWebApi.Models._ResponseModel.Catalog;
using System.Web;
using System.Web.Helpers;
using System.IO;
using PushSharp;
using PushSharp.Core;
using Nop.Core.Infrastructure;
using Newtonsoft.Json;
using PushSharp.Apple;
using PushSharp.Android;
using System.Web.Mvc;
using Nop.Plugin.Misc.BsWebApi.Models.SliderImageModel;


namespace Nop.Plugin.Misc.BsWebApi.Controllers
{

    public class BsWebApiConfigurationController : BasePluginController
    {
        #region Fields

        private const string IconFilePath = "Plugins/Misc.BsWebApi/Content/IconPackage";

        private readonly IWorkContext _workContext;
        private readonly IBsNopMobilePluginService _nopMobileService;
        private readonly IPluginFinder _pluginFinder;
        private readonly ICategoryService _categoryService;
        private readonly IManufacturerService _manufacturerService;
        private readonly IStoreContext _storeContext;
        private readonly IStoreService _storeService;
        private readonly IPictureService _pictureService;
        private readonly BsNopMobileSettings _webApiSettings;
        private readonly ISettingService _settingService;
        private readonly IPermissionService _permissionService;
        private readonly IProductService _productService;
        private readonly ILocalizationService _localizationService;
        private readonly IVendorService _vendorService;
        private readonly IContentManagementTemplateService _contentManagementTemplateService;
        private readonly IContentManagementService _contentManagementService;
        private readonly ILanguageService _languageService;
        private readonly ILocalizedEntityService _localizedEntityService;
        private readonly IStoreMappingService _storeMappingService;
        private readonly IUrlRecordService _urlRecordService;

        private readonly IBS_SliderService _bsSliderService;

        private readonly IWebHelper _webHelper;
        private readonly ICategoryIconService _categoryIconService;
        private readonly IDeviceService _deviceService;
        private readonly IDownloadService _downloadService;

        #endregion

        public BsWebApiConfigurationController(IWorkContext workContext,
            IBsNopMobilePluginService nopMobileService,
            IBS_SliderService bsSliderService,
            IWebHelper webHelper,
            IProductService productService,
            ICategoryService categoryService,
            IManufacturerService manufacturerService,
            IPluginFinder pluginFinder,
            BsNopMobileSettings webApiSettings,
            ISettingService settingService,
            IPermissionService permissionService,
            IStoreContext storeContext,
            ILocalizationService localizationService,
            IStoreService storeService,
            IVendorService vendorService,
            IPictureService pictureService,
            IContentManagementTemplateService contentManagementTemplateService,
            IContentManagementService contentManagementService,
            ILanguageService languageService,
            ILocalizedEntityService localizedEntityService,
            IStoreMappingService storeMappingService,
            IUrlRecordService urlRecordService,
            ICategoryIconService categoryIconService,
            IDeviceService deviceService,
            IDownloadService downloadService
            )
        {
            this._categoryService = categoryService;
            this._vendorService = vendorService;
            this._manufacturerService = manufacturerService;
            this._workContext = workContext;
            this._webHelper = webHelper;
            this._nopMobileService = nopMobileService;
            this._pluginFinder = pluginFinder;
            this._webApiSettings = webApiSettings;
            this._localizationService = localizationService;
            this._settingService = settingService;
            this._permissionService = permissionService;
            this._storeContext = storeContext;
            this._storeService = storeService;
            this._pictureService = pictureService;
            this._productService = productService;
            this._contentManagementTemplateService = contentManagementTemplateService;
            this._contentManagementService = contentManagementService;
            this._languageService = languageService;
            this._localizedEntityService = localizedEntityService;
            this._storeMappingService = storeMappingService;
            this._urlRecordService = urlRecordService;
            this._categoryIconService = categoryIconService;
            this._deviceService = deviceService;
            this._downloadService = downloadService;
            this._bsSliderService = bsSliderService;
        }


        #region Utilities

        [NonAction]
        protected virtual void PrepareTemplatesModel(TopicModel model)
        {
            if (model == null)
                throw new ArgumentNullException("model");

            var templates = _contentManagementTemplateService.GetAllTopicTemplates();
            foreach (var template in templates)
            {
                model.AvailableTopicTemplates.Add(new SelectListItem
                {
                    Text = template.Name,
                    Value = template.Id.ToString()
                });
            }
        }

        [NonAction]
        protected virtual void UpdateLocales(BS_ContentManagement topic, TopicModel model)
        {
            foreach (var localized in model.Locales)
            {
                _localizedEntityService.SaveLocalizedValue(topic,
                                                               x => x.Title,
                                                               localized.Title,
                                                               localized.LanguageId);

                _localizedEntityService.SaveLocalizedValue(topic,
                                                           x => x.Body,
                                                           localized.Body,
                                                           localized.LanguageId);

                _localizedEntityService.SaveLocalizedValue(topic,
                                                           x => x.MetaKeywords,
                                                           localized.MetaKeywords,
                                                           localized.LanguageId);

                _localizedEntityService.SaveLocalizedValue(topic,
                                                           x => x.MetaDescription,
                                                           localized.MetaDescription,
                                                           localized.LanguageId);

                _localizedEntityService.SaveLocalizedValue(topic,
                                                           x => x.MetaTitle,
                                                           localized.MetaTitle,
                                                           localized.LanguageId);

                //search engine name
                var seName = topic.ValidateSeName(localized.SeName, localized.Title, false);
                _urlRecordService.SaveSlug(topic, seName, localized.LanguageId);
            }
        }

        [NonAction]
        protected virtual void PrepareStoresMappingModel(TopicModel model, BS_ContentManagement topic, bool excludeProperties)
        {
            if (model == null)
                throw new ArgumentNullException("model");

            //model.AvailableStores = _storeService.GetAllStores().Select(s => s.ToModel())
            //    .ToList();
            if (!excludeProperties)
            {
                if (topic != null)
                {
                    model.SelectedStoreIds = _storeMappingService.GetStoresIdsWithAccess(topic);
                }
            }
        }

        [NonAction]
        protected virtual void SaveStoreMappings(BS_ContentManagement topic, TopicModel model)
        {
            var existingStoreMappings = _storeMappingService.GetStoreMappings(topic);
            var allStores = _storeService.GetAllStores();
            foreach (var store in allStores)
            {
                if (model.SelectedStoreIds != null && model.SelectedStoreIds.Contains(store.Id))
                {
                    //new store
                    if (existingStoreMappings.Count(sm => sm.StoreId == store.Id) == 0)
                        _storeMappingService.InsertStoreMapping(topic, store.Id);
                }
                else
                {
                    //remove store
                    var storeMappingToDelete = existingStoreMappings.FirstOrDefault(sm => sm.StoreId == store.Id);
                    if (storeMappingToDelete != null)
                        _storeMappingService.DeleteStoreMapping(storeMappingToDelete);
                }
            }
        }

        [NonAction]
        private List<SelectListItem> GetSubCategories()
        {
            var categories = _categoryService.GetAllCategories();

Views/WebApi/CategoryIcons.cshtml
@model Nop.Plugin.Misc.BsWebApi.Models.DashboardModel.CategoryIconsModel
@{
    Layout = "~/Administration/Views/Shared/_AdminLayout.cshtml";
}
@using Nop.Web.Framework;
@using Nop.Core.Infrastructure;
@using System.Globalization;
@Html.Action("StoreScopeConfiguration", "Setting", new { area = "Admin" })
@using (Html.BeginForm())
{ @Html.AntiForgeryToken()
    @Html.Partial("~/Plugins/Misc.BsWebApi/Views/WebApi/_NopMobileMenu.cshtml")
    <div class="plugincontainer">
        <div class="configurecontaincontainer">
            <div class="storelocatersettingtitle">
                <strong>@T("Plugins.NopMobile.WebApi.categoryiconTitle")</strong>
            </div>
            
            <div>
                <table class="adminContent">
                    @*<tr>
                            <td class="adminTitle">
                                @Html.OverrideStoreCheckboxFor(model => model.Willusedefaultnopcategory_OverrideForStore, model => model.Willusedefaultnopcategory, Model.ActiveStoreScopeConfiguration)
                                @Html.NopLabelFor(model => model.Willusedefaultnopcategory):
                            </td>
                            <td class="adminData">
                                @Html.EditorFor(model => model.Willusedefaultnopcategory)
                                @Html.ValidationMessageFor(model => model.Willusedefaultnopcategory)
                            </td>
                        </tr>*@

                    <tr>
                        <td class="adminTitle">
                            @*@Html.OverrideStoreCheckboxFor(model => model.Willusedefaultnopcategory_OverrideForStore, model => model.Willusedefaultnopcategory, Model.ActiveStoreScopeConfiguration)*@
                            @Html.NopLabelFor(model => model.SubCategoryId):
                        </td>
                        <td class="adminData">
                            @Html.DropDownListFor(model => model.SubCategoryId, Model.AvailableSubCategories,"Please select a category")
                            @Html.ValidationMessageFor(model => model.SubCategoryId)
                        </td>
                    </tr>
                    <tr>
                        <td class="adminTitle">
                            @*@Html.OverrideStoreCheckboxFor(model => model.Willusedefaultnopcategory_OverrideForStore, model => model.Willusedefaultnopcategory, Model.ActiveStoreScopeConfiguration)*@
                            @Html.NopLabelFor(model => model.Extension):
                        </td>
                        <td class="adminData">
                            @*@Html.EditorFor(model => model.SubCategoryIcon)
                            @Html.ValidationMessageFor(model => model.SubCategoryIcon)*@
                            @*<input name="files" id="files" type="file" />*@
                            <div class="demo-section k-content">
                                <input type="file" name="files" id="files" />
                            </div>
                            
                        </td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>
                            <input type="submit" name="save" class="k-button" value="@T("Admin.Common.Save")" />
                        </td>
                    </tr>
                </table>
            </div>

            <div class="subcategory-list">
                <div id="subcategories-grid"></div>

                    <script>
                        $(document).ready(function () {
                            $("#subcategories-grid").kendoGrid({
                                dataSource: {
                                    type: "json",
                                    transport: {
                                        read: {
                                            url: "@Html.Raw(Url.Action("SubCategoryList", "BsWebApiConfiguration"))",
                                            type: "POST",
                                            dataType: "json"
                                        },
                                        destroy: {
                                            url: "@Html.Raw(Url.Action("SubCategoryListDelete", "BsWebApiConfiguration"))",
                                            type: "POST",
                                            dataType: "json"
                                        }
                                    },
                                    schema: {
                                        data: "Data",
                                        total: "Total",
                                        errors: "Errors",
                                        model: {
                                            id: "Id",
                                            fields: {
                                                Name: { editable: false},
                                                IconPath: { editable: false}
                                            }
                                        }
                                    },
                                    requestEnd: function (e) {
                                        if (e.type != "read") {
                                           // this.read();
                                        }
                                    },
                                    error: function (e) {
                                        // display_kendoui_grid_error(e);
                                        // Cancel the changes
                                        this.cancelChanges();
                                    },
                                    serverPaging: true,
                                    serverFiltering: true,
                                    serverSorting: true
                                },
                                pageable: {
                                    refresh: true,
                                    numeric: false,
                                    previousNext: false,
                                    info: false
                                },
                                editable: {
                                    confirmation: true,
                                    mode: "inline"
                                },
                                scrollable: false,
                                columns: [
                                {
                                    field: "Name",
                                    title: "Category Name"
                                },{
                                    field: "IconPath",
                                    title: "Icon",
                                    template: '<img src="#=IconPath#?nocache='+ new Date().getTime() + '" />'
                                },
                                {
                                    command: [{
                                        name: "destroy",
                                        text: "@T("Admin.Common.Delete")"
                                    }],
                                    width: 200
                                }]
                            });
                        });

                    </script>
                
            </div>
        </div>
    </div>
}
@*<script>
    $(document).ready(function () {
        $("#files").kendoUpload({

        });
    });
</script>*@


<script id="fileTemplate" type="text/x-kendo-template">
    <span class='k-progress'></span>
    <div class='file-wrapper'>
        <span class='file-icon #=addExtensionClass(files[0].extension)#'></span>
        <h4 class='file-heading file-name-heading'>Name: #=name#</h4>
        <h4 class='file-heading file-size-heading'>Size: #=size# bytes</h4>
        <button type='button' class='k-upload-action'></button>
    </div>
</script>

<script>
    $(document).ready(function () {
        $("#files").kendoUpload({                        
            template: kendo.template($('#fileTemplate').html())
        });
    });

    function addExtensionClass(extension) {
        switch (extension) {
            case '.jpg':
            case '.img':
            case '.png':
            case '.gif':
                return "img-file";
            case '.doc':
            case '.docx':
                return "doc-file";
            case '.xls':
            case '.xlsx':
                return "xls-file";
            case '.pdf':
                return "pdf-file";
            case '.zip':
            case '.rar':
                return "zip-file";
            default:
                return "default-file";
        }
    }
</script>

<style>
    .file-icon {
        display: inline-block;
        float: left;
        width: 48px;
        height: 48px;
        margin-left: 10px;
        margin-top: 13.5px;
    }

    .img-file {
        background-image: url(../content/web/upload/jpg.png);
    }

    .doc-file {
        background-image: url(../content/web/upload/doc.png);
    }

    .pdf-file {
        background-image: url(../content/web/upload/pdf.png);
    }

    .xls-file {
        background-image: url(../content/web/upload/xls.png);
    }

    .zip-file {
        background-image: url(../content/web/upload/zip.png);
    }

    .default-file {
        background-image: url(../content/web/upload/default.png);
    }

    #example .file-heading {
        font-family: Arial;
        font-size: 1.1em;
        display: inline-block;
        float: left;
        width: 60%;
        margin: 0 0 0 20px;
        height: 25px;
        -ms-text-overflow: ellipsis;
        -o-text-overflow: ellipsis;
        text-overflow: ellipsis;
        overflow: hidden;
        white-space: nowrap;
    }

    #example .file-name-heading {
        font-weight: bold;
        margin-top: 20px;
    }

    #example .file-size-heading {
        font-weight: normal;
        font-style: italic;
    }

    li.k-file .file-wrapper .k-upload-action {
        position: absolute;
        top: 0;
        right: 0;
    }

    li.k-file div.file-wrapper {
        position: relative;
        height: 75px;
    }
</style>

Views/WebApi/ContentManagement.cshtml
@model Nop.Plugin.Misc.BsWebApi.Models.DashboardModel.ContentManagementModel
@{
    Layout = "~/Administration/Views/Shared/_AdminLayout.cshtml";
}
@using Nop.Web.Framework;
@using Nop.Core.Infrastructure;
@using System.Globalization;
@Html.Action("StoreScopeConfiguration", "Setting", new { area = "Admin" })
@using (Html.BeginForm())
{ @Html.AntiForgeryToken()
    @Html.Partial("~/Plugins/Misc.BsWebApi/Views/WebApi/_NopMobileMenu.cshtml")
    <div class="plugincontainer">
        <div class="configurecontaincontainer">
            <div class="storelocatersettingtitle">
                <strong>@T("Plugins.NopMobile.WebApi.contentmanagementTitle")</strong>
            </div>
            <div>
                <table class="adminContent">
                    <tr>
                        <td class="adminTitle">
                            @Html.OverrideStoreCheckboxFor(model => model.DefaultNopFlowSameAs_OverrideForStore, model => model.DefaultNopFlowSameAs, Model.ActiveStoreScopeConfiguration)
                            @Html.NopLabelFor(model => model.DefaultNopFlowSameAs):
                        </td>
                        <td class="adminData">
                            @Html.EditorFor(model => model.DefaultNopFlowSameAs)
                            @Html.ValidationMessageFor(model => model.DefaultNopFlowSameAs)
                        </td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>
                            <input type="submit" name="save" class="k-button" value="@T("Admin.Common.Save")" />
                        </td>
                    </tr>

                </table>
            </div>
            <hr style=" margin: 15px 0;" />
            <div class="section-header">
                <div class="title">
                    <img src="@Url.Content("~/Administration/Content/images/ico-content.png")" alt="" />
                    @T("Admin.ContentManagement.Topics")
                </div>
                <div class="options">
                    <a href="@Url.Action("Create")" class="k-button">@T("Admin.Common.AddNew")</a>
                </div>
            </div>
            @*<table width="100%">
                    <tr>
                        <td class="adminTitle">
                            @Html.NopLabelFor(model => model.SearchStoreId):
                        </td>
                        <td class="adminData">
                            @Html.DropDownList("SearchStoreId", Model.AvailableStores)
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <input type="button" id="search-topics" class="k-button" value="@T("Admin.Common.Search")" />
                        </td>
                    </tr>
                </table>*@
            <table class="adminContent">
                <tr>
                    <td>
                        <div id="topics-grid"></div>

                        <script>
                $(document).ready(function () {
                    $("#topics-grid").kendoGrid({
                        dataSource: {
                            type: "json",
                            transport: {
                                read: {
                                    url: "@Html.Raw(Url.Action("ContentManagementList", "BsWebApiConfiguration"))",
                                    type: "POST",
                                    dataType: "json",
                                    data: additionalData
                                }
                            },
                            schema: {
                                data: "Data",
                                total: "Total",
                                errors: "Errors"
                            },
                            error: function(e) {
                                display_kendoui_grid_error(e);
                                // Cancel the changes
                                this.cancelChanges();
                            },
                            serverPaging: true,
                            serverFiltering: true,
                            serverSorting: true
                        },
                        pageable: {
                            refresh: true,
                            numeric: false,
                            previousNext: false,
                            info: false
                        },
                        editable: {
                            confirmation: false,
                            mode: "inline"
                        },
                        scrollable: false,
                        columns: [{
                            field: "SystemName",
                            title: "@T("Admin.ContentManagement.Topics.Fields.SystemName")"
                        }, {
                            field: "IsPasswordProtected",
                            title: "@T("Admin.ContentManagement.Topics.Fields.IsPasswordProtected")",
                            width: 100,
                            headerAttributes: { style: "text-align:center" },
                            attributes: { style: "text-align:center" },
                            template: '<img src="@Url.Content("~/Administration/Content/images/")active-#=IsPasswordProtected#.gif" />'
                        }, {
                            field: "IncludeInSitemap",
                            title: "@T("Admin.ContentManagement.Topics.Fields.IncludeInSitemap")",
                            width: 100,
                            headerAttributes: { style: "text-align:center" },
                            attributes: { style: "text-align:center" },
                            template: '<img src="@Url.Content("~/Administration/Content/images/")active-#=IncludeInSitemap#.gif" />'
                        }, {
                            field: "IncludeInTopMenu",
                            title: "@T("Admin.ContentManagement.Topics.Fields.IncludeInTopMenu")",
                            width: 100,
                            headerAttributes: { style: "text-align:center" },
                            attributes: { style: "text-align:center" },
                            template: '<img src="@Url.Content("~/Administration/Content/images/")active-#=IncludeInTopMenu#.gif" />'
                        }, {
                            field: "IncludeInFooterColumn1",
                            title: "@T("Admin.ContentManagement.Topics.Fields.IncludeInFooterColumn1")",
                            width: 100,
                            headerAttributes: { style: "text-align:center" },
                            attributes: { style: "text-align:center" },
                            template: '<img src="@Url.Content("~/Administration/Content/images/")active-#=IncludeInFooterColumn1#.gif" />'
                        }, {
                            field: "IncludeInFooterColumn2",
                            title: "@T("Admin.ContentManagement.Topics.Fields.IncludeInFooterColumn2")",
                            width: 100,
                            headerAttributes: { style: "text-align:center" },
                            attributes: { style: "text-align:center" },
                            template: '<img src="@Url.Content("~/Administration/Content/images/")active-#=IncludeInFooterColumn2#.gif" />'
                        }, {
                            field: "IncludeInFooterColumn3",
                            title: "@T("Admin.ContentManagement.Topics.Fields.IncludeInFooterColumn3")",
                            width: 100,
                            headerAttributes: { style: "text-align:center" },
                            attributes: { style: "text-align:center" },
                            template: '<img src="@Url.Content("~/Administration/Content/images/")active-#=IncludeInFooterColumn3#.gif" />'
                        }, {
                            field: "DisplayOrder",
                            title: "@T("Admin.ContentManagement.Topics.Fields.DisplayOrder")",
                            width: 100
                        }, {
                            field: "Id",
                            title: "@T("Admin.Common.Edit")",
                            width: 100,
                            template: '<a href="Edit/#=Id#">@T("Admin.Common.Edit")</a>'
                        }]
                    });
                });
                        </script>

                        <script type="text/javascript">

                $(document).ready(function () {
                    //search button
                    $('#search-topics').click(function () {
                        //search
                        var grid = $('#topics-grid').data('kendoGrid');
                        grid.dataSource.read();
                        return false;
                    });
                });

                function additionalData() {
                    var data = {
                        SearchStoreId: $('#SearchStoreId').val()
                    };
                    addAntiForgeryToken(data);
                    return data;
                }
                        </script>
                    </td>
                </tr>
            </table>
        </div>


    </div>
}

Views/WebApi/_NopMobileMenu.cshtml
<div class="supportmenu">
    <link href="~/Plugins/Misc.BsWebApi/Content/styles.css" rel="stylesheet" />
    <div class="section-header">
        <div class="title">
            @*@T("Plugins.NopMobile.WebApi.menu")*@
            BS Mobile WebApi
        </div>
    </div>
    <ul class="supportmenu_ul">
        <a href="/Admin/Widget/ConfigureWidget?systemName=BrainStation.BsWebApi" class="menulink">
            <li class="menu_li">@T("Plugins.NopMobile.WebApi.overview")</li>
        </a>

        <a href="@Url.Action("Generalsetting", "BsWebApiConfiguration")" class="menulink">
            <li class="menu_li">@T("Plugins.NopMobile.WebApi.generalsetting")</li>
        </a>

        <a href="@Url.Action("Theme", "BsWebApiConfiguration")" class="menulink">
            <li class="menu_li">@T("Plugins.NopMobile.WebApi.themepersonalization")</li>
        </a>

        <a href="@Url.Action("BannerSlider", "BsWebApiConfiguration")" class="menulink">
            <li class="menu_li">@T("Plugins.NopMobile.WebApi.bannericon")</li>
        </a>

        <a href="@Url.Action("ContentManagement", "BsWebApiConfiguration")" class="menulink">
            <li class="menu_li">@T("Plugins.NopMobile.WebApi.contantmanegement")</li>
        </a>

        <a href="@Url.Action("PushNotification", "BsWebApiConfiguration")" class="menulink">
            <li class="menu_li">@T("Plugins.NopMobile.WebApi.pushnotification")</li>
        </a>

        <a href="@Url.Action("CategoryIcons", "BsWebApiConfiguration")" class="menulink">
            <li class="menu_li">@T("Plugins.NopMobile.WebApi.categoryicon")</li>
        </a>
        <a href="@Url.Action("MobileWebSiteSetting", "BsWebApiConfiguration")" class="menulink">
            <li class="menu_li">@T("Plugins.NopMobile.WebApi.mobilewebsitesetting")</li>
        </a>
        <a href="@Url.Action("ContactInfo", "BsWebApiConfiguration" )" class="menulink">
            <li class="menu_li">@T("Plugins.NopMobile.WebApi.contactInfo")</li>
        </a>
        <a href="@Url.Action("SliderImage", "BsWebApiConfiguration")" class="menulink">
            <li class="menu_li">@T("Plugins.NopMobile.WebApi.Slider")</li>
        </a>
    </ul>
</div>